### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by semseysandor** [es-progress/zephyr#4]
Layout for docs:

- [x] Home #102
- [x] Install: How to install Zephyr project #87 
- [x] Setup profiles: How to create profiles #98 
- [x] Create ISO #99
- [x] Ubuntu install #100 
    - Pre-install: partitioning
    - Post-install: post-Install
- [x] Customize: How to run Zephyr/customize Ubuntu #101 
- [x] Know-how: #104 
- [x] Reference
    - [x] zephyrctl #105 
    - [x] configs #106
    - [x] modules #106
    - [x] disk-maps #111 

Extra jobs
- [x] add cross-links to pages #107 
- [x] README.md #107 
- [ ] proof-reading #113
