### ISSUE TITLE
Whitelisting/blacklisting customizations

### ISSUE THREAD

**Issue by semseysandor** [es-progress/zephyr#51]
Filter available customizations e.g: I don't use jmeter, so I don't want it installed and configured.
Also filter specific configs: if not defined skip.

With whitelist you can opt-in to specific customizations, with blacklist you can opt-out.

- [x] White/blacklist from config #114
- [x] White/blacklist from CLI #114 
- [ ] allow selecting module groups (e.g. apps, system) #115
